# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x03\x61pi\"E\n\x1bGetListRecommendUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03ids\x18\x02 \x03(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"+\n\x1cGetListRecommendUserResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\xbf\x01\n\x11\x43reateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12sexual_orientation\x18\x02 \x01(\t\x12\x19\n\x11relationship_goal\x18\x03 \x01(\t\x12\x10\n\x08passions\x18\x04 \x03(\t\x12\x0c\n\x04pets\x18\x05 \x01(\t\x12\x0f\n\x07workout\x18\x06 \x01(\t\x12\x0f\n\x07smoking\x18\x07 \x01(\t\x12\x16\n\x0esleeping_habit\x18\x08 \x01(\t\x12\r\n\x05score\x18\t \x01(\r\"(\n\x12\x43reateUserResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32\xa6\x01\n\x04User\x12]\n\x14getListRecommendUser\x12 .api.GetListRecommendUserRequest\x1a!.api.GetListRecommendUserResponse\"\x00\x12?\n\ncreateUser\x12\x16.api.CreateUserRequest\x1a\x17.api.CreateUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETLISTRECOMMENDUSERREQUEST']._serialized_start=19
  _globals['_GETLISTRECOMMENDUSERREQUEST']._serialized_end=88
  _globals['_GETLISTRECOMMENDUSERRESPONSE']._serialized_start=90
  _globals['_GETLISTRECOMMENDUSERRESPONSE']._serialized_end=133
  _globals['_CREATEUSERREQUEST']._serialized_start=136
  _globals['_CREATEUSERREQUEST']._serialized_end=327
  _globals['_CREATEUSERRESPONSE']._serialized_start=329
  _globals['_CREATEUSERRESPONSE']._serialized_end=369
  _globals['_USER']._serialized_start=372
  _globals['_USER']._serialized_end=538
# @@protoc_insertion_point(module_scope)
